title: "Rohan Sen"
title_separator: ""
description: "Research in kernel methods, financial econometrics, and statistical learning."
url: "https://rohansen-8.github.io"
baseurl: ""
theme: jekyll-theme-minimal

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

author:
  name: "Rohan Sen"

profile_picture: assets/img/photo.jpeg
profile_title: "PhD in Econometrics and Statistics"
profile_affiliation: "Università della Svizzera italiana (USI)"
profile_affiliation_url: "https://www.usi.ch/en"
research_interests: "Kernel Methods, Financial Econometrics, Statistical Learning"
